### PR TITLE
Enhance Feign-Vertx to use an optional CircuitBreak and @Fallback annotation

### PR DESCRIPTION
**Pull request by GordonMcKinney**
I've added the option to add a circuit breaker to the Feign-Vertx client.

I've also added an optional @Fallback annotation which can be used to specify open-circuit behavior using zero boilerplate.

See unit test Class VertxCircuitBreakerTest

Hope you like the enhancement!

### CODE REVIEW

**Comment by GordonMcKinney** [comment]
@hosuaby LMK if you have questions. I've added a simple builder circuitBreaker() method and a new feature @Fallback.

**Comment by hosuaby** [comment]
Hello Gordon,
I carefully studied your PR. Perhaps, I will not accept it. I wanna keep this library focused on client generation. Circuit-breaking in not in its scope. Introducing it, will make bring to client a new dependency (vertx-circuit-breaker) with potentially incompatible version, and make API more tricky.
`feign-vertx` already marry perfectly with `vertx-circuit-breaker`. Certainly, wrap all calls with CircuitBreakerExecutor can be verbose, but can easily be done with small helper like:

```java
  private static class CircuitBreakerExecutor {
    private static final CircuitBreaker breaker = CircuitBreaker.create("my-circuit-breaker", vertx,
        new CircuitBreakerOptions().setMaxFailures(5).setTimeout(2000)
    );

    public static <T> Future<T> executeAndReportWithFallback(Supplier<Future<T>> action, Function<Throwable, T> fallback) {
      Future<T> f = Future.future();

      breaker
          .executeAndReportWithFallback(f, future -> {
            action.get().setHandler((AsyncResult<T> res) -> {
              if (res.succeeded()) {
                future.complete(res.result());
              } else {
                future.fail(res.cause());
              }
            });
          }, fallback);

      return f;
    }
  }

  // ... later

      SomeApi client = VertxFeign
        .builder()
        .vertx(vertx)
        .decoder(new JacksonDecoder(TestUtils.MAPPER))
        .target(SomeApi.class, "http://localhost:8089");

      CircuitBreakerExecutor
        .executeAndReportWithFallback(() -> client.getSynonyms("blabla"), (ignored) -> Collections.singleton("bib"))
        .setHandler(res -> { /* logic */ });
```

**Comment by hosuaby** [comment]
@GordonMcKinney when you have enhancement idea if better to create an issue before. The only possible enhancement I see is to add a support to client-side load-balancing.
This plugin exists because feign-core doesn't support asynchronous clients. Creation of AsynchronousMethodHandler (that will handle CompletableFuture return type) in feign core will open the possibility to run feign on all kind of asynchronous clients, and the need for a separate library like feign-vertx will disappear.

**Comment by GordonMcKinney** [comment]
We took time as a team to carefully evaluate what we need for our production services. We like, and use, Spring Cloud library which supports circuit breaker and fallback functionality - with zero boilerplate. Having the same functionality for Vertx is very important to us.

I love that your library aids in reducing boilerplate code. Adding the option of a circuit breaker and @Fallback without extra boilerplate is an amazingly useful. This capability is something we'll use moving forward in production.

I understand your concern regarding library maintenance. This is why I've been so motivated to help by making contributions to you.

We don't plan to add new features to this project (we've got what we need with this PR). We do plan to identify and fix bugs moving forward, using this branch as our baseline. I am available to investigate new issues if you don't have time to do so. LMK!

I hope you reconsider your thoughts on this PR.

Sincerely, Gordon McKinney.

**Comment by GordonMcKinney** [comment]
PS. Java CompletableFuture uses a thread pool, this doesn't scale to the concurrency we run in production.

**Comment by hosuaby** [comment]
I agree with idea to reduce boilerplate code. But It's not in this library that defects of API of `vertx-circuit-breaker` must be fixed.  At least, from my point of view.

**Pull request closed without merging**
