### PR TITLE
Update feign-vertx to be compatible with openfeign, java 11+

### PR DESCRIPTION
**Pull request by garyschulteog**
Switch to openfeign 10.10.x from netflix 8.x,
bump to vert 3.6
bump to jacoco-plugin 0.8.6 (for java 11+)

bump revision to 0.2.0

### CODE REVIEW

**Comment by hosuaby** [comment]
Hello, @garyschulteog . Thanks for PR. I will check it ASAP

**Comment by garyschulteog** [comment]
@hosuaby do you have a timeline for if/when a 0.2.0 version of feign-vertx would be published to public maven repos?

**Comment by hosuaby** [comment]
Some problem with Travis build. When it psss, it will become available. I hope tomorrow

**Comment by hosuaby** [comment]
@garyschulteog It's publicly published. At that moment I am workling on implementation supporting multiple versions of Vertx and Feign. Starting from version 1.0.0 will need to follow compatibility table to choose right version of plugin to use;

**Comment by garyschulteog** [comment]
> @garyschulteog It's publicly published. At that moment I am workling on implementation supporting multiple versions of Vertx

Thank you.  I considered that there should be a version matrix of some sort, but figured that is best left to the primary maintainer(s).

Much appreciated

**Comment by hosuaby** [comment]
Hello @garyschulteog 

Since 1 may 2021 JCenter will be disabled. I migrated artifacts starting from vertion 1.0.0 to Maven Central. For your needs, I recommend you to switch on version 3.0.0.

If you update ether Vertx or Feign, please, follow the version matrix in README.

Best

**Pull request merged**
