### PR TITLE
junit-jupiter should be test scoped

### PR DESCRIPTION
**Pull request by jebl01**

### CODE REVIEW

**Comment by jebl01** [comment]
Would it be possible to release this as a patch to version 4? We are still on Vert.x 3.9...

**Comment by hosuaby** [comment]
Thanks for your contribution @jebl01 
Yes, I will backport this fix ASAP.

**Comment by jebl01** [comment]
>Yes, I will backport this fix ASAP

♥️

**Comment by hosuaby** [comment]
@jebl01 your fix now available in `4.0.1`. Conglaturation!

**Pull request merged**
